# Generated by Django 5.0 on 2023-12-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_tracker_createdat_alter_tracker_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='createdAt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='updatedAt',
            field=models.IntegerField(),
        ),
    ]
