# Generated by Django 5.0 on 2023-12-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_tracker_createdat_alter_tracker_updatedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='tracker',
            name='timestamp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
