# Generated by Django 5.0 on 2023-12-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_tracker_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
