# Generated by Django 5.0 on 2023-12-12 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_tracker_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
